name: Pipeline

on:
  push:
    branches: 
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-javav@3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: | 
          mvn clean
          mvn package
